GET http://localhost:3003/character

####

PUT http://localhost:3003/character
content-type: application/json

{
    "name": "Deadpool",
    "gender": "MALE",
    "description": "Sexy Motherf***"
}

####


DELETE http://localhost:3003/character/10